# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# 親のパス
food = Category.create(name: "食品")
drink = Category.create(name: "飲料")
daily_necessities = Category.create(name: "日用品")
interior_residence_accessory = Category.create(name: "防災用品")
book_music_game = Category.create(name: "医療品")
toy_hobby_goods = Category.create(name: "家電・電池類")
cosme_perfume_beauty = Category.create(name: "コスメ・香水・美容")
others = Category.create(name: "その他")

# 食品
food_1 = food.children.create(name: "生鮮食品")
food_1.children.create([{name: "果物"},{name: "野菜"},{name: "生鮮魚"},{name: "貝類"},{name: "牛肉"},{name: "豚肉"},{name: "鶏肉"},{name: "混合肉(その他)"},{name: "卵"},{name: "きのこ（菌）類"},{name: "その他の生鮮食品"}])
food_2 = food.children.create(name: "パン系")
food_2.children.create([{name: "食パン"},{name: "菓子パン"},{name: "惣菜パン"},{name: "サンドウィッチ"},{name: "バゲット"},{name: "クロワッサン"},{name: "マフィン"},{name: "ナン"},{name: "ドーナッツ"},{name: "その他のパン"}])
food_3 = food.children.create(name: "調味料")
food_3.children.create([{name: "塩"},{name: "砂糖"},{name: "酢"},{name: "醤油"},{name: "塩胡椒"},{name: "料理酒"},{name: "みりん"},{name: "一味/七味"},{name: "味噌"},{name: "鶏ガラ"},{name: "味の素"},{name: "その他の調味料"}])
food_4 = food.children.create(name: "乳製品(食品)")
food_4.children.create([{name: "ヨーグルト"},{name: "バター"},{name: "マーガリン"},{name: "チーズ"},{name: "練乳"},{name: "クリーム"},{name: "全粒乳"},{name: "その他の乳製品"}])
food_5 = food.children.create(name: "インスタント食品")
food_5.children.create([{name: "カップ麺"},{name: "袋麺"},{name: "米飯"},{name: "カレー"},{name: "クリームシチュー"},{name: "丼料理の具材"},{name: "煮物"},{name: "増えるワカメ"},{name: "焼きそば"},{name: "うどん"},{name: "味噌汁/吸い物"},{name: "その他のインスタント食品"}])
food_6 = food.children.create(name: "缶詰類")
food_6.children.create([{name: "ツナ缶"},{name: "サバ缶"},{name: "カットフルーツ"},{name: "にしん"},{name: "コーン"},{name: "貝缶"},{name: "果物"}])
food_7 = food.children.create(name: "菓子")
food_7.children.create([{name: "スナック菓子"},{name: "チョコレート"},{name: "ゼリー"},{name: "せんべい"},{name: "飴"},{name: "グミ"},{name: "ラムネ"},{name: "ピーナッツ"},{name: "ガム"},{name: "クッキー"},{name: "ビスケット"},{name: "その他のお菓子"}])
food_8 = food.children.create(name: "おつまみ")
food_8.children.create([{name: "さきいか系"},{name: "コーン系"},{name: "昆布系"},{name: "チーズ系"},{name: "スナック系"},{name: "アーモンド系"},{name: "チョコ系"},{name: "フライ系"},{name: "その他のおつまみ"}])
food_9 = food.children.create(name: "その他の食品")
food_9.children.create([{name: "未知なる食品"}])

# 飲料
drink_1 = drink.children.create(name: "水")
drink_1.children.create([{name: "軟水"},{name: "硬水"},{name: "炭酸水"},{name: "ポロシャツ"},{name: "タンクトップ"},{name: "ニット/セーター"},{name: "パーカー"},{name: "カーディガン"},{name: "スウェット"},{name: "ジャージ"},{name: "ベスト"},{name: "その他の水"}])
drink_2 = drink.children.create(name: "清涼飲料")
drink_2.children.create([{name: "炭酸飲料"},{name: "果物系ジュース"},{name: "野菜ジュース"},{name: "スポーツドリンク"},{name: "緑茶"},{name: "烏龍茶"},{name: "紅茶"},{name: "ミルクティー"},{name: "コーヒー"},{name: "その他の清涼飲料"}])
drink_3 = drink.children.create(name: "酒類")
drink_3.children.create([{name: "ビール"},{name: "発泡酒"},{name: "酎ハイ"},{name: "芋焼酎"},{name: "麦焼酎"},{name: "日本酒"},{name: "赤ワイン"},{name: "白ワイン"},{name: "ハイボール"},{name: "ウイスキー"},{name: "カクテル"},{name: "その他の酒類"}])
drink_4 = drink.children.create(name: "乳製品(飲料)")
drink_4.children.create([{name: "牛乳"},{name: "豆乳"},{name: "乳酸菌飲料"},{name: "飲むヨーグルト"},{name: "その他の乳製品飲料"}])
drink_5 = drink.children.create(name: "その他")
drink_5.children.create([{name: "その他の飲料"}])

# 日用品
daily_necessities_1 = daily_necessities.children.create(name: "キッチン用品")
daily_necessities_1.children.create([{name: "食器用洗剤"},{name: "ラップ"},{name: "換気扇フィルター"},{name: "アルコール"},{name: "キッチンペーパー"},{name: "アルミホイル"},{name: "クッキングペーパー"},{name: "キッチンハイター"},{name: "手袋"},{name: "輪ゴム"},{name: "その他"}])
daily_necessities_2 = daily_necessities.children.create(name: "食器")
daily_necessities_2.children.create([{name: "皿"},{name: "茶碗"},{name: "どんぶり"},{name: "グラス"},{name: "湯呑み"},{name: "カップ"},{name: "ジョッキ"},{name: "弁当箱"},{name: "タッパー"},{name: "計量カップ"},{name: "その他"}])
daily_necessities_3 = daily_necessities.children.create(name: "調理器具")
daily_necessities_3.children.create([{name: "皿"},{name: "箸"},{name: "スプーン"},{name: "フォーク"},{name: "菜箸"},{name: "お玉"},{name: "計量カップ"},{name: "計量器"},{name: "フライパン"},{name: "お鍋"},{name: "その他"}])
daily_necessities_4 = daily_necessities.children.create(name: "洗濯用品")
daily_necessities_4.children.create([{name: "洗濯用洗剤(液体)"},{name: "洗濯用洗剤(固形/粉末)"},{name: "柔軟剤"},{name: "重曹"},{name: "洗濯のり"},{name: "漂白剤"},{name: "洗濯用ネット"},{name: "その他"}])
daily_necessities_5 = daily_necessities.children.create(name: "トイレ用品")
daily_necessities_5.children.create([{name: "トイレットペーパー"},{name: "トイレ用洗剤"},{name: "トイレ用ナプキン"},{name: "芳香剤"},{name: "消臭剤"},{name: "消臭スプレー"},{name: "ブラシ"},{name: "その他"}])
daily_necessities_6 = daily_necessities.children.create(name: "ゴミ袋")
daily_necessities_6.children.create([{name: "5L以下"},{name: "10L"},{name: "15L"},{name: "20L"},{name: "30L"},{name: "45L"},{name: "70L"},{name: "90L"},{name: "100L"},{name: "120L"},{name: "130L"},{name: "150L"},{name: "大型"},{name: "特大"},{name: "その他"}])
daily_necessities_7 = daily_necessities.children.create(name: "ティッシュペーパー")
daily_necessities_7.children.create([{name: "ボックスティッシュ"},{name: "ポケットティッシュ"},{name: "トイレに流せるティッシュ"},{name: "贅沢なティッシュ"},{name: "その他"}])
daily_necessities_8 = daily_necessities.children.create(name: "マスク")
daily_necessities_8.children.create([{name: "不織布"},{name: "サージカル"},{name: "防塵"},{name: "防毒"},{name: "ガーゼ"},{name: "布"},{name: "ポリウレタン"},{name: "その他"}])
daily_necessities_9 = daily_necessities.children.create(name: "タオル")
daily_necessities_9.children.create([{name: "ハンドタオル"},{name: "キッチンタオル"},{name: "バスタオル"},{name: "ハンカチ"},{name: "その他"}])
daily_necessities_10 = daily_necessities.children.create(name: "文房具")
daily_necessities_10.children.create([{name: "ボールペン"},{name: "マジック"},{name: "消しゴム"},{name: "ノリ"},{name: "定規"},{name: "クリアファイル"},{name: "シャーペン"},{name: "鉛筆"},{name: "その他"}])
daily_necessities_11 = daily_necessities.children.create(name: "その他")
daily_necessities_11.children.create([{name: "その他の日用品"}])

# 防災用品
interior_residence_accessory_1 = interior_residence_accessory.children.create(name: "キッチン/食器")
interior_residence_accessory_1.children.create([{name: "食器"},{name: "調理器具"},{name: "収納/キッチン雑貨"},{name: "弁当用品"},{name: "カトラリー(スプーン等)"},{name: "テーブル用品"},{name: "容器"},{name: "エプロン"},{name: "アルコールグッズ"},{name: "浄水機"},{name: "その他"}])
interior_residence_accessory_2 = interior_residence_accessory.children.create(name: "ベッド/マットレス")
interior_residence_accessory_2.children.create([{name: "セミシングルベッド"},{name: "シングルベッド"},{name: "セミダブルベッド"},{name: "ダブルベッド"},{name: "ワイドダブルベッド"},{name: "クイーンベッド"},{name: "キングベッド"},{name: "脚付きマットレスベッド"},{name: "マットレス"},{name: "すのこベッド"},{name: "ロフトベッド/システムベッド"},{name: "簡易ベッド/折りたたみベッド"},{name: "収納付き"},{name: "その他"}])
interior_residence_accessory_3 = interior_residence_accessory.children.create(name: "ソファ/ソファベッド")
interior_residence_accessory_3.children.create([{name: "ソファセット"},{name: "シングルソファ"},{name: "ラブソファ"},{name: "トリプルソファ"},{name: "オットマン"},{name: "コーナーソファ"},{name: "ビーズソファ/クッションソファ"},{name: "ローソファ/フロアソファ"},{name: "ソファベッド"},{name: "応接セット"},{name: "ソファカバー"},{name: "リクライニングソファ"},{name: "その他"}])
interior_residence_accessory_4 = interior_residence_accessory.children.create(name: "椅子/チェア")
interior_residence_accessory_4.children.create([{name: "一般"},{name: "スツール"},{name: "ダイニングチェア"},{name: "ハイバックチェア"},{name: "ロッキングチェア"},{name: "座椅子"},{name: "折り畳みイス"},{name: "デスクチェア"},{name: "その他"}])
interior_residence_accessory_5 = interior_residence_accessory.children.create(name: "机/テーブル")
interior_residence_accessory_5.children.create([{name: "こたつ"},{name: "カウンターテーブル"},{name: "サイドテーブル"},{name: "センターテーブル"},{name: "ダイニングテーブル"},{name: "座卓/ちゃぶ台"},{name: "アウトドア用"},{name: "パソコン用"},{name: "事務机/学習机"},{name: "その他"}])
interior_residence_accessory_6 = interior_residence_accessory.children.create(name: "収納家具")
interior_residence_accessory_6.children.create([{name: "リビング収納"},{name: "キッチン収納"},{name: "玄関/屋外収納"},{name: "バス/トイレ収納"},{name: "本収納"},{name: "本/CD/DVD収納"},{name: "洋服タンス/押入れ収納"},{name: "電話台/ファックス台"},{name: "ドレッサー/鏡台"},{name: "棚/ラック"},{name: "ケース/ボックス"},{name: "その他"}])
interior_residence_accessory_7 = interior_residence_accessory.children.create(name: "ラグ/カーペット/マット")
interior_residence_accessory_7.children.create([{name: "ラグ"},{name: "カーペット"},{name: "ホットカーペット"},{name: "玄関/キッチンマット"},{name: "トイレ/バスマット"},{name: "その他"}])
interior_residence_accessory_8 = interior_residence_accessory.children.create(name: "カーテン/ブラインド")
interior_residence_accessory_8.children.create([{name: "カーテン"},{name: "ブラインド"},{name: "ロールスクリーン"},{name: "のれん"},{name: "その他"}])
interior_residence_accessory_9 = interior_residence_accessory.children.create(name: "ライト/照明")
interior_residence_accessory_9.children.create([{name: "蛍光灯/電球"},{name: "天井照明"},{name: "フロアスタンド"},{name: "その他"}])
interior_residence_accessory_10 = interior_residence_accessory.children.create(name: "寝具")
interior_residence_accessory_10.children.create([{name: "布団/毛布"},{name: "枕"},{name: "シーツ/カバー"},{name: "その他"}])
interior_residence_accessory_11 = interior_residence_accessory.children.create(name: "インテリア小物")
interior_residence_accessory_11.children.create([{name: "ごみ箱"},{name: "ウェルカムボード"},{name: "オルゴール"},{name: "クッション"},{name: "クッションカバー"},{name: "スリッパラック"},{name: "ティッシュボックス"},{name: "バスケット/かご"},{name: "フォトフレーム"},{name: "マガジンラック"},{name: "モビール"},{name: "モビール"},{name: "花瓶"},{name: "灰皿"},{name: "傘立て"},{name: "小物入れ"},{name: "置時計"},{name: "掛時計/柱時計"},{name: "鏡(立て掛け式)"},{name: "鏡(壁掛け式)"},{name: "置物"},{name: "風鈴"},{name: "植物/観葉植物"},{name: "その他"}])
interior_residence_accessory_12 = interior_residence_accessory.children.create(name: "季節/年中行事")
interior_residence_accessory_12.children.create([{name: "正月"},{name: "成人式"},{name: "バレンタインデー"},{name: "ひな祭り"},{name: "子どもの日"},{name: "母の日"},{name: "父の日"},{name: "父の日"},{name: "サマーギフト/お中元"},{name: "夏/夏休み"},{name: "ハロウィン"},{name: "敬老の日"},{name: "七五三"},{name: "お歳暮"},{name: "クリスマス"},{name: "冬一般"},{name: "その他"}])
interior_residence_accessory_13 = interior_residence_accessory.children.create(name: "その他")
interior_residence_accessory_13.children.create([{name: "すべて"}])

# 医療品
book_music_game_1 = book_music_game.children.create(name: "本")
book_music_game_1.children.create([{name: "文学/小説"},{name: "人文/社会"},{name: "ノンフィクション/教養"},{name: "地図/旅行ガイド"},{name: "ビジネス/経済"},{name: "ビジネス/経済"},{name: "健康/医学"},{name: "コンピュータ/IT"},{name: "趣味/スポーツ/実用"},{name: "住まい/暮らし/子育て"},{name: "アート/エンタメ"},{name: "洋書"},{name: "絵本"},{name: "参考書"},{name: "その他"}])
book_music_game_2 = book_music_game.children.create(name: "漫画")
book_music_game_2.children.create([{name: "全巻セット"},{name: "少年漫画"},{name: "少女漫画"},{name: "青年漫画"},{name: "女性漫画"},{name: "同人誌"},{name: "その他"}])
book_music_game_3 = book_music_game.children.create(name: "雑誌")
book_music_game_3.children.create([{name: "アート/エンタメ/ホビー"},{name: "ファッション"},{name: "ニュース/総合"},{name: "趣味/スポーツ"},{name: "その他"}])
book_music_game_4 = book_music_game.children.create(name: "CD")
book_music_game_4.children.create([{name: "邦楽"},{name: "洋楽"},{name: "アニメ"},{name: "クラシック"},{name: "K-POP/アジア"},{name: "キッズ/ファミリー"},{name: "その他"}])
book_music_game_5 = book_music_game.children.create(name: "DVD/ブルーレイ")
book_music_game_5.children.create([{name: "外国映画"},{name: "日本映画"},{name: "アニメ"},{name: "TVドラマ"},{name: "ミュージック"},{name: "お笑い/バラエティ"},{name: "スポーツ/フィットネス"},{name: "キッズ/ファミリー"},{name: "その他"}])
book_music_game_6 = book_music_game.children.create(name: "レコード")
book_music_game_6.children.create([{name: "邦楽"},{name: "洋楽"},{name: "その他"}])
book_music_game_7 = book_music_game.children.create(name: "テレビゲーム")
book_music_game_7.children.create([{name: "家庭用ゲーム本体"},{name: "家庭用ゲームソフト"},{name: "携帯用ゲーム本体"},{name: "携帯用ゲームソフト"},{name: "PCゲーム"},{name: "その他"}])

# 家電・電池類
toy_hobby_goods_1 = toy_hobby_goods.children.create(name: "おもちゃ")
toy_hobby_goods_1.children.create([{name: "キャラクターグッズ"},{name: "ぬいぐるみ"},{name: "小物/アクセサリー"},{name: "模型/プラモデル"},{name: "ミニカー"},{name: "トイラジコン"},{name: "プラモデル"},{name: "ホビーラジコン"},{name: "鉄道模型"},{name: "その他"}])
toy_hobby_goods_2 = toy_hobby_goods.children.create(name: "タレントグッズ")
toy_hobby_goods_2.children.create([{name: "アイドル"},{name: "ミュージシャン"},{name: "タレント/お笑い芸人"},{name: "スポーツ選手"},{name: "その他"}])
toy_hobby_goods_3 = toy_hobby_goods.children.create(name: "コミック/アニメグッズ")
toy_hobby_goods_3.children.create([{name: "ストラップ"},{name: "キーホルダー"},{name: "バッジ"},{name: "カード"},{name: "クリアファイル"},{name: "ポスター"},{name: "タオル"},{name: "その他"}])
toy_hobby_goods_4 = toy_hobby_goods.children.create(name: "トレーディングカード")
toy_hobby_goods_4.children.create([{name: "遊戯王"},{name: "マジック：ザ・ギャザリング"},{name: "ポケモンカードゲーム"},{name: "デュエルマスターズ"},{name: "バトルスピリッツ"},{name: "プリパラ"},{name: "アイカツ"},{name: "カードファイト!! ヴァンガード"},{name: "ヴァイスシュヴァルツ"},{name: "プロ野球オーナーズリーグ"},{name: "ベースボールヒーローズ"},{name: "ドラゴンボール"},{name: "スリーブ"},{name: "その他"}])
toy_hobby_goods_5 = toy_hobby_goods.children.create(name: "フィギュア")
toy_hobby_goods_5.children.create([{name: "コミック/アニメ"},{name: "特撮"},{name: "ゲームキャラクター"},{name: "SF/ファンタジー/ホラー"},{name: "アメコミ"},{name: "スポーツ"},{name: "ミリタリー"},{name: "その他"}])
toy_hobby_goods_6 = toy_hobby_goods.children.create(name: "楽器/器材")
toy_hobby_goods_6.children.create([{name: "エレキギター"},{name: "アコースティックギター"},{name: "ベース"},{name: "エフェクター"},{name: "アンプ"},{name: "弦楽器"},{name: "管楽器"},{name: "鍵盤楽器"},{name: "打楽器"},{name: "和楽器"},{name: "楽譜/スコア"},{name: "レコーディング/PA機器"},{name: "DJ機器"},{name: "DTM/DAW"},{name: "その他"}])
toy_hobby_goods_7 = toy_hobby_goods.children.create(name: "コレクション")
toy_hobby_goods_7.children.create([{name: "武具"},{name: "使用済切手/官製はがき"},{name: "旧貨幣/金貨/銀貨/記念硬貨"},{name: "印刷物"},{name: "ノベルティグッズ"},{name: "その他"}])
toy_hobby_goods_8 = toy_hobby_goods.children.create(name: "ミリタリー")
toy_hobby_goods_8.children.create([{name: "トイガン"},{name: "個人装備"},{name: "その他"}])
toy_hobby_goods_9 = toy_hobby_goods.children.create(name: "美術品")
toy_hobby_goods_9.children.create([{name: "陶芸"},{name: "ガラス"},{name: "漆芸"},{name: "金属工芸"},{name: "絵画/タペストリ"},{name: "版画"},{name: "彫刻/オブジェクト"},{name: "書"},{name: "写真"},{name: "その他"}])
toy_hobby_goods_10 = toy_hobby_goods.children.create(name: "アート用品")
toy_hobby_goods_10.children.create([{name: "画材"},{name: "額縁"},{name: "その他"}])
toy_hobby_goods_11 = toy_hobby_goods.children.create(name: "その他")
toy_hobby_goods_11.children.create([{name: "トランプ/UNO"},{name: "カルタ/百人一首"},{name: "ダーツ"},{name: "ビリヤード"},{name: "麻雀"},{name: "パズル/ジグソーパズル"},{name: "囲碁/将棋"},{name: "オセロ/チェス"},{name: "人生ゲーム"},{name: "野球/サッカーゲーム"},{name: "スポーツ"},{name: "三輪車/乗り物"},{name: "ヨーヨー"},{name: "模型製作用品"},{name: "鉄道"},{name: "航空機"},{name: "アマチュア無線"},{name: "パチンコ/パチスロ"},{name: "その他"}])

# コスメ・香水・美容
cosme_perfume_beauty_1 = cosme_perfume_beauty.children.create(name: "ベースメイク")
cosme_perfume_beauty_1.children.create([{name: "ファンデーション"},{name: "化粧下地"},{name: "コントロールカラー"},{name: "BBクリーム"},{name: "CCクリーム"},{name: "コンシーラー"},{name: "フェイスパウダー"},{name: "トライアルセット/サンプル"},{name: "その他"}])
cosme_perfume_beauty_2 = cosme_perfume_beauty.children.create(name: "メイクアップ")
cosme_perfume_beauty_2.children.create([{name: "アイシャドウ"},{name: "口紅"},{name: "リップグロス"},{name: "リップライナー"},{name: "チーク"},{name: "フェイスカラー"},{name: "マスカラ"},{name: "アイライナー"},{name: "つけまつげ"},{name: "アイブロウペンシル"},{name: "パウダーアイブロウ"},{name: "眉マスカラ"},{name: "トライアルセット/サンプル"},{name: "メイク道具/化粧小物"},{name: "美顔用品/美顔ローラー"},{name: "その他"}])
cosme_perfume_beauty_3 = cosme_perfume_beauty.children.create(name: "ネイルケア")
cosme_perfume_beauty_3.children.create([{name: "ネイルカラー"},{name: "カラージェル"},{name: "ネイルベースコート/トップコート"},{name: "ネイルアート用品"},{name: "ネイルパーツ"},{name: "ネイルチップ/付け爪"},{name: "手入れ用具"},{name: "除光液"},{name: "その他"}])
cosme_perfume_beauty_4 = cosme_perfume_beauty.children.create(name: "香水")
cosme_perfume_beauty_4.children.create([{name: "香水(女性用)"},{name: "香水(男性用)"},{name: "ユニセックス"},{name: "ボディミスト"},{name: "その他"}])
cosme_perfume_beauty_5 = cosme_perfume_beauty.children.create(name: "スキンケア/基礎化粧品")
cosme_perfume_beauty_5.children.create([{name: "化粧水/ローション"},{name: "乳液/ミルク"},{name: "美容液"},{name: "フェイスクリーム"},{name: "洗顔料"},{name: "クレンジング/メイク落とし"},{name: "パック/フェイスマスク"},{name: "ジェル/ゲル"},{name: "ブースター/導入液"},{name: "アイケア"},{name: "リップケア"},{name: "トライアルセット/サンプル"},{name: "洗顔グッズ"},{name: "その他"}])
cosme_perfume_beauty_6 = cosme_perfume_beauty.children.create(name: "ヘアケア")
cosme_perfume_beauty_6.children.create([{name: "シャンプー"},{name: "トリートメント"},{name: "コンディショナー"},{name: "リンス"},{name: "スタイリング剤"},{name: "カラーリング剤"},{name: "ブラシ"},{name: "その他"}])
cosme_perfume_beauty_7 = cosme_perfume_beauty.children.create(name: "ボディケア")
cosme_perfume_beauty_7.children.create([{name: "オイル/クリーム"},{name: "ハンドクリーム"},{name: "ローション"},{name: "日焼け止め/サンオイル"},{name: "ボディソープ"},{name: "入浴剤"},{name: "制汗/デオドラント"},{name: "フットケア"},{name: "その他"}])
cosme_perfume_beauty_8 = cosme_perfume_beauty.children.create(name: "オーラルケア")
cosme_perfume_beauty_8.children.create([{name: "口臭防止/エチケット用品"},{name: "歯ブラシ"},{name: "その他"}])
cosme_perfume_beauty_9 = cosme_perfume_beauty.children.create(name: "リラクゼーション")
cosme_perfume_beauty_9.children.create([{name: "エッセンシャルオイル"},{name: "芳香器"},{name: "お香/香炉"},{name: "キャンドル"},{name: "リラクゼーショングッズ"},{name: "その他"}])
cosme_perfume_beauty_10 = cosme_perfume_beauty.children.create(name: "ダイエット")
cosme_perfume_beauty_10.children.create([{name: "ダイエット食品"},{name: "エクササイズ用品"},{name: "体重計"},{name: "体脂肪計"},{name: "その他"}])
cosme_perfume_beauty_11 = cosme_perfume_beauty.children.create(name: "その他")
cosme_perfume_beauty_11.children.create([{name: "健康用品"},{name: "看護/介護用品"},{name: "救急/衛生用品"},{name: "その他"}])

# その他
others_1 = others.children.create(name: "まとめ売り")
others_1.children.create([{name: "すべて"}])
others_2 = others.children.create(name: "ペット用品")
others_2.children.create([{name: "ペットフード"},{name: "犬用品"},{name: "猫用品"},{name: "魚用品/水草"},{name: "小動物用品"},{name: "爬虫類/両生類用品"},{name: "かご/おり"},{name: "鳥用品"},{name: "虫類用品"},{name: "その他"}])
others_3 = others.children.create(name: "食品")
others_3.children.create([{name: "菓子"},{name: "米"},{name: "野菜"},{name: "果物"},{name: "調味料"},{name: "魚介類(加工食品)"},{name: "肉類(加工食品)"},{name: "その他 加工食品"},{name: "その他"}])
others_4 = others.children.create(name: "飲料/酒")
others_4.children.create([{name: "コーヒー"},{name: "ソフトドリンク"},{name: "ミネラルウォーター"},{name: "茶"},{name: "ウイスキー"},{name: "ワイン"},{name: "ブランデー"},{name: "焼酎"},{name: "日本酒"},{name: "ビール、発泡酒"},{name: "その他"}])
others_5 = others.children.create(name: "日用品/生活雑貨/旅行")
others_5.children.create([{name: "タオル/バス用品"},{name: "日用品/生活雑貨"},{name: "洗剤/柔軟剤"},{name: "旅行用品"},{name: "防災関連グッズ"},{name: "その他"}])
others_6 = others.children.create(name: "アンティーク/コレクション")
others_6.children.create([{name: "雑貨"},{name: "工芸品"},{name: "家具"},{name: "印刷物"},{name: "その他"}])
others_7 = others.children.create(name: "文房具/事務用品")
others_7.children.create([{name: "筆記具"},{name: "ノート/メモ帳"},{name: "テープ/マスキングテープ"},{name: "カレンダー/スケジュール"},{name: "アルバム/スクラップ"},{name: "ファイル/バインダー"},{name: "はさみ/カッター"},{name: "カードホルダー/名刺管理"},{name: "のり/ホッチキス"},{name: "その他"}])
others_8 = others.children.create(name: "事務/店舗用品")
others_8.children.create([{name: "オフィス用品一般"},{name: "オフィス家具"},{name: "店舗用品"},{name: "OA機器"},{name: "ラッピング/包装"},{name: "その他"}])
others_9 = others.children.create(name: "その他")
others_9.children.create([{name: "すべて"}])