# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# 親のパス
food = Category.create(name: "食品")
drink = Category.create(name: "飲料")
daily_necessities = Category.create(name: "日用品")
disaster_prevention = Category.create(name: "防災用品")
medical_supplies = Category.create(name: "医療品")
cosme_perfume_beauty = Category.create(name: "コスメ・香水・美容")
others = Category.create(name: "その他")

# 食品
food_1 = food.children.create(name: "生鮮食品")
food_1.children.create([{name: "果物"},{name: "野菜"},{name: "生鮮魚"},{name: "貝類"},{name: "牛肉"},{name: "豚肉"},{name: "鶏肉"},{name: "混合肉(その他)"},{name: "卵"},{name: "きのこ（菌）類"},{name: "その他の生鮮食品"}])
food_2 = food.children.create(name: "パン系")
food_2.children.create([{name: "食パン"},{name: "菓子パン"},{name: "惣菜パン"},{name: "サンドウィッチ"},{name: "バゲット"},{name: "クロワッサン"},{name: "マフィン"},{name: "ナン"},{name: "ドーナッツ"},{name: "その他のパン"}])
food_3 = food.children.create(name: "調味料")
food_3.children.create([{name: "塩"},{name: "砂糖"},{name: "酢"},{name: "醤油"},{name: "塩胡椒"},{name: "料理酒"},{name: "みりん"},{name: "一味/七味"},{name: "味噌"},{name: "鶏ガラ"},{name: "味の素"},{name: "その他の調味料"}])
food_4 = food.children.create(name: "乳製品(食品)")
food_4.children.create([{name: "ヨーグルト"},{name: "バター"},{name: "マーガリン"},{name: "チーズ"},{name: "練乳"},{name: "クリーム"},{name: "全粒乳"},{name: "その他の乳製品"}])
food_5 = food.children.create(name: "インスタント食品")
food_5.children.create([{name: "カップ麺"},{name: "袋麺"},{name: "米飯"},{name: "カレー"},{name: "クリームシチュー"},{name: "丼料理の具材"},{name: "煮物"},{name: "増えるワカメ"},{name: "焼きそば"},{name: "うどん"},{name: "味噌汁/吸い物"},{name: "その他のインスタント食品"}])
food_6 = food.children.create(name: "缶詰類")
food_6.children.create([{name: "ツナ缶"},{name: "サバ缶"},{name: "カットフルーツ"},{name: "にしん"},{name: "コーン"},{name: "貝缶"},{name: "果物"}])
food_7 = food.children.create(name: "菓子")
food_7.children.create([{name: "スナック菓子"},{name: "チョコレート"},{name: "ゼリー"},{name: "せんべい"},{name: "飴"},{name: "グミ"},{name: "ラムネ"},{name: "ピーナッツ"},{name: "ガム"},{name: "クッキー"},{name: "ビスケット"},{name: "その他のお菓子"}])
food_8 = food.children.create(name: "おつまみ")
food_8.children.create([{name: "さきいか系"},{name: "コーン系"},{name: "昆布系"},{name: "チーズ系"},{name: "スナック系"},{name: "アーモンド系"},{name: "チョコ系"},{name: "フライ系"},{name: "その他のおつまみ"}])
food_9 = food.children.create(name: "その他の食品")
food_9.children.create([{name: "未知なる食品"}])

# 飲料
drink_1 = drink.children.create(name: "水")
drink_1.children.create([{name: "軟水"},{name: "硬水"},{name: "炭酸水"},{name: "ポロシャツ"},{name: "タンクトップ"},{name: "ニット/セーター"},{name: "パーカー"},{name: "カーディガン"},{name: "スウェット"},{name: "ジャージ"},{name: "ベスト"},{name: "その他の水"}])
drink_2 = drink.children.create(name: "清涼飲料")
drink_2.children.create([{name: "炭酸飲料"},{name: "果物系ジュース"},{name: "野菜ジュース"},{name: "スポーツドリンク"},{name: "緑茶"},{name: "烏龍茶"},{name: "紅茶"},{name: "ミルクティー"},{name: "コーヒー"},{name: "その他の清涼飲料"}])
drink_3 = drink.children.create(name: "酒類")
drink_3.children.create([{name: "ビール"},{name: "発泡酒"},{name: "酎ハイ"},{name: "芋焼酎"},{name: "麦焼酎"},{name: "日本酒"},{name: "赤ワイン"},{name: "白ワイン"},{name: "ハイボール"},{name: "ウイスキー"},{name: "カクテル"},{name: "その他の酒類"}])
drink_4 = drink.children.create(name: "乳製品(飲料)")
drink_4.children.create([{name: "牛乳"},{name: "豆乳"},{name: "乳酸菌飲料"},{name: "飲むヨーグルト"},{name: "その他の乳製品飲料"}])
drink_5 = drink.children.create(name: "その他")
drink_5.children.create([{name: "その他の飲料"}])

# 日用品
daily_necessities_1 = daily_necessities.children.create(name: "キッチン用品")
daily_necessities_1.children.create([{name: "食器用洗剤"},{name: "ラップ"},{name: "換気扇フィルター"},{name: "アルコール"},{name: "キッチンペーパー"},{name: "アルミホイル"},{name: "クッキングペーパー"},{name: "キッチンハイター"},{name: "手袋"},{name: "輪ゴム"},{name: "その他"}])
daily_necessities_2 = daily_necessities.children.create(name: "食器")
daily_necessities_2.children.create([{name: "皿"},{name: "茶碗"},{name: "どんぶり"},{name: "グラス"},{name: "湯呑み"},{name: "カップ"},{name: "ジョッキ"},{name: "弁当箱"},{name: "タッパー"},{name: "計量カップ"},{name: "その他"}])
daily_necessities_3 = daily_necessities.children.create(name: "調理器具")
daily_necessities_3.children.create([{name: "皿"},{name: "箸"},{name: "スプーン"},{name: "フォーク"},{name: "菜箸"},{name: "お玉"},{name: "計量カップ"},{name: "計量器"},{name: "フライパン"},{name: "お鍋"},{name: "その他"}])
daily_necessities_4 = daily_necessities.children.create(name: "洗濯用品")
daily_necessities_4.children.create([{name: "洗濯用洗剤(液体)"},{name: "洗濯用洗剤(固形/粉末)"},{name: "柔軟剤"},{name: "重曹"},{name: "洗濯のり"},{name: "漂白剤"},{name: "洗濯用ネット"},{name: "その他"}])
daily_necessities_5 = daily_necessities.children.create(name: "トイレ用品")
daily_necessities_5.children.create([{name: "トイレットペーパー"},{name: "トイレ用洗剤"},{name: "トイレ用ナプキン"},{name: "芳香剤"},{name: "消臭剤"},{name: "消臭スプレー"},{name: "ブラシ"},{name: "その他"}])
daily_necessities_6 = daily_necessities.children.create(name: "ゴミ袋")
daily_necessities_6.children.create([{name: "5L以下"},{name: "10L"},{name: "15L"},{name: "20L"},{name: "30L"},{name: "45L"},{name: "70L"},{name: "90L"},{name: "100L"},{name: "120L"},{name: "130L"},{name: "150L"},{name: "大型"},{name: "特大"},{name: "その他"}])
daily_necessities_7 = daily_necessities.children.create(name: "ティッシュペーパー")
daily_necessities_7.children.create([{name: "ボックスティッシュ"},{name: "ポケットティッシュ"},{name: "トイレに流せるティッシュ"},{name: "贅沢なティッシュ"},{name: "その他"}])
daily_necessities_8 = daily_necessities.children.create(name: "マスク")
daily_necessities_8.children.create([{name: "不織布"},{name: "サージカル"},{name: "防塵"},{name: "防毒"},{name: "ガーゼ"},{name: "布"},{name: "ポリウレタン"},{name: "その他"}])
daily_necessities_9 = daily_necessities.children.create(name: "タオル")
daily_necessities_9.children.create([{name: "ハンドタオル"},{name: "キッチンタオル"},{name: "バスタオル"},{name: "ハンカチ"},{name: "その他"}])
daily_necessities_10 = daily_necessities.children.create(name: "文房具")
daily_necessities_10.children.create([{name: "ボールペン"},{name: "マジック"},{name: "消しゴム"},{name: "ノリ"},{name: "定規"},{name: "クリアファイル"},{name: "シャーペン"},{name: "鉛筆"},{name: "その他"}])
daily_necessities_11 = daily_necessities.children.create(name: "その他")
daily_necessities_11.children.create([{name: "その他の日用品"}])

# 防災用品
disaster_prevention_1 = disaster_prevention.children.create(name: "飲料")
disaster_prevention_1.children.create([{name: "水"},{name: "お茶"},{name: "栄養ドリンク"},{name: "その他"}])
disaster_prevention_2 = disaster_prevention.children.create(name: "食品")
disaster_prevention_2.children.create([{name: "乾パン"},{name: "缶詰"},{name: "レトルト"},{name: "インスタント食品"},{name: "飴"},{name: "チョコレート"},{name: "アルファ米"},{name: "カロリーメイト"},{name: "その他"}])
disaster_prevention_3 = disaster_prevention.children.create(name: "食器/調理器具")
disaster_prevention_3.children.create([{name: "古紙/新聞紙"},{name: "カセットコンロ"},{name: "カセットボンベ"},{name: "ラップ"},{name: "アルミホイル"},{name: "紙コップ"},{name: "紙皿"},{name: "割り箸"},{name: "チャッカマン"},{name: "ライター"},{name: "その他"}])
disaster_prevention_4 = disaster_prevention.children.create(name: "電気製品")
disaster_prevention_4.children.create([{name: "発電機"},{name: "乾電池"},{name: "ラジオ"},{name: "蓄電用バッテリー"},{name: "携帯用充電器"},{name: "懐中電灯"},{name: "その他"}])
disaster_prevention_5 = disaster_prevention.children.create(name: "装備品/工具")
disaster_prevention_5.children.create([{name: "スコップ"},{name: "運動靴"},{name: "長靴"},{name: "手袋"},{name: "工具セット"},{name: "ほうき"},{name: "ちりとり"},{name: "ロープ"},{name: "ビニールシート"},{name: "その他"}])
disaster_prevention_6 = disaster_prevention.children.create(name: "衛生用品")
disaster_prevention_6.children.create([{name: "マスク"},{name: "消毒液"},{name: "ティッシュペーパー"},{name: "ウェットティッシュ"},{name: "生理用品"},{name: "簡易トイレ"},{name: "マウスウォッシュ"},{name: "その他"}])
disaster_prevention_7 = disaster_prevention.children.create(name: "医療品")
disaster_prevention_7.children.create([{name: "絆創膏"},{name: "包帯"},{name: "胃腸薬"},{name: "便秘薬"},{name: "持病の薬"},{name: "体温計"},{name: "ガーゼ"},{name: "アルコール"},{name: "エタノール"},{name: "ビタミン剤"},{name: "その他"}])
disaster_prevention_8 = disaster_prevention.children.create(name: "防寒用品")
disaster_prevention_8.children.create([{name: "携帯用カイロ"},{name: "毛布"},{name: "マフラー"},{name: "手袋"},{name: "その他"}])
disaster_prevention_9 = disaster_prevention.children.create(name: "雑貨")
disaster_prevention_9.children.create([{name: "化粧品"},{name: "ろうそく"},{name: "ランタン"},{name: "タオル"},{name: "安全ピン"},{name: "ハンカチ"},{name: "テープ"},{name: "ビニール袋"},{name: "その他"}])
disaster_prevention_10 = disaster_prevention.children.create(name: "その他")
disaster_prevention_10.children.create([{name: "その他の防災品"}])

# 医療品
medical_supplies_1 = medical_supplies.children.create(name: "精神神経薬")
medical_supplies_1.children.create([{name: "風邪薬"},{name: "解熱鎮痛薬"},{name: "催眠鎮痛薬"},{name: "眠気防止薬"},{name: "酔い止め薬"},{name: "その他"}])
medical_supplies_2 = medical_supplies.children.create(name: "消化器官用薬")
medical_supplies_2.children.create([{name: "制酸薬"},{name: "健胃薬"},{name: "整腸薬"},{name: "消化薬"},{name: "胃腸鎮鎮痙薬"},{name: "止瀉薬"},{name: "瀉下薬"},{name: "浣腸薬"},{name: "駆虫薬"},{name: "その他"}])
medical_supplies_3 = medical_supplies.children.create(name: "循環器/血液用薬")
medical_supplies_3.children.create([{name: "強心薬"},{name: "血管補強薬"},{name: "動脈硬化用薬"},{name: "貧血用薬"},{name: "その他"}])
medical_supplies_4 = medical_supplies.children.create(name: "呼吸器官用薬")
medical_supplies_4.children.create([{name: "鎮咳去痰薬"},{name: "含嗽薬"},{name: "その他"}])
medical_supplies_5 = medical_supplies.children.create(name: "女性用薬")
medical_supplies_5.children.create([{name: "婦人薬"},{name: "避妊薬"},{name: "その他"}])
medical_supplies_6 = medical_supplies.children.create(name: "外皮用薬")
medical_supplies_6.children.create([{name: "殺菌消毒薬"},{name: "殺菌消毒薬"},{name: "皮膚炎用薬"},{name: "みずむし用薬"},{name: "毛髪用薬"},{name: "その他"}])
medical_supplies_7 = medical_supplies.children.create(name: "その他の薬品")
medical_supplies_7.children.create([{name: "耳鼻科用薬"},{name: "歯科口腔用薬"},{name: "禁煙補助薬"},{name: "漢方製剤"},{name: "生薬"},{name: "公衆衛生用薬"},{name: "一般検査薬"},{name: "その他"}])

# コスメ・香水・美容
cosme_perfume_beauty_1 = cosme_perfume_beauty.children.create(name: "ベースメイク")
cosme_perfume_beauty_1.children.create([{name: "ファンデーション"},{name: "化粧下地"},{name: "コントロールカラー"},{name: "BBクリーム"},{name: "CCクリーム"},{name: "コンシーラー"},{name: "フェイスパウダー"},{name: "トライアルセット/サンプル"},{name: "その他"}])
cosme_perfume_beauty_2 = cosme_perfume_beauty.children.create(name: "メイクアップ")
cosme_perfume_beauty_2.children.create([{name: "アイシャドウ"},{name: "口紅"},{name: "リップグロス"},{name: "リップライナー"},{name: "チーク"},{name: "フェイスカラー"},{name: "マスカラ"},{name: "アイライナー"},{name: "つけまつげ"},{name: "アイブロウペンシル"},{name: "パウダーアイブロウ"},{name: "眉マスカラ"},{name: "トライアルセット/サンプル"},{name: "メイク道具/化粧小物"},{name: "美顔用品/美顔ローラー"},{name: "その他"}])
cosme_perfume_beauty_3 = cosme_perfume_beauty.children.create(name: "ネイルケア")
cosme_perfume_beauty_3.children.create([{name: "ネイルカラー"},{name: "カラージェル"},{name: "ネイルベースコート/トップコート"},{name: "ネイルアート用品"},{name: "ネイルパーツ"},{name: "ネイルチップ/付け爪"},{name: "手入れ用具"},{name: "除光液"},{name: "その他"}])
cosme_perfume_beauty_4 = cosme_perfume_beauty.children.create(name: "香水")
cosme_perfume_beauty_4.children.create([{name: "香水(女性用)"},{name: "香水(男性用)"},{name: "ユニセックス"},{name: "ボディミスト"},{name: "その他"}])
cosme_perfume_beauty_5 = cosme_perfume_beauty.children.create(name: "スキンケア/基礎化粧品")
cosme_perfume_beauty_5.children.create([{name: "化粧水/ローション"},{name: "乳液/ミルク"},{name: "美容液"},{name: "フェイスクリーム"},{name: "洗顔料"},{name: "クレンジング/メイク落とし"},{name: "パック/フェイスマスク"},{name: "ジェル/ゲル"},{name: "ブースター/導入液"},{name: "アイケア"},{name: "リップケア"},{name: "トライアルセット/サンプル"},{name: "洗顔グッズ"},{name: "その他"}])
cosme_perfume_beauty_6 = cosme_perfume_beauty.children.create(name: "ヘアケア")
cosme_perfume_beauty_6.children.create([{name: "シャンプー"},{name: "トリートメント"},{name: "コンディショナー"},{name: "リンス"},{name: "スタイリング剤"},{name: "カラーリング剤"},{name: "ブラシ"},{name: "その他"}])
cosme_perfume_beauty_7 = cosme_perfume_beauty.children.create(name: "ボディケア")
cosme_perfume_beauty_7.children.create([{name: "オイル/クリーム"},{name: "ハンドクリーム"},{name: "ローション"},{name: "日焼け止め/サンオイル"},{name: "ボディソープ"},{name: "入浴剤"},{name: "制汗/デオドラント"},{name: "フットケア"},{name: "その他"}])
cosme_perfume_beauty_8 = cosme_perfume_beauty.children.create(name: "オーラルケア")
cosme_perfume_beauty_8.children.create([{name: "口臭防止/エチケット用品"},{name: "歯ブラシ"},{name: "その他"}])
cosme_perfume_beauty_9 = cosme_perfume_beauty.children.create(name: "リラクゼーション")
cosme_perfume_beauty_9.children.create([{name: "エッセンシャルオイル"},{name: "芳香器"},{name: "お香/香炉"},{name: "キャンドル"},{name: "リラクゼーショングッズ"},{name: "その他"}])
cosme_perfume_beauty_10 = cosme_perfume_beauty.children.create(name: "ダイエット")
cosme_perfume_beauty_10.children.create([{name: "ダイエット食品"},{name: "エクササイズ用品"},{name: "体重計"},{name: "体脂肪計"},{name: "その他"}])
cosme_perfume_beauty_11 = cosme_perfume_beauty.children.create(name: "その他")
cosme_perfume_beauty_11.children.create([{name: "健康用品"},{name: "看護/介護用品"},{name: "救急/衛生用品"},{name: "その他"}])

# その他
others_1 = others.children.create(name: "まとめ売り")
others_1.children.create([{name: "すべて"}])
others_2 = others.children.create(name: "ペット用品")
others_2.children.create([{name: "ペットフード"},{name: "犬用品"},{name: "猫用品"},{name: "魚用品/水草"},{name: "小動物用品"},{name: "爬虫類/両生類用品"},{name: "かご/おり"},{name: "鳥用品"},{name: "虫類用品"},{name: "その他"}])
others_3 = others.children.create(name: "食品")
others_3.children.create([{name: "菓子"},{name: "米"},{name: "野菜"},{name: "果物"},{name: "調味料"},{name: "魚介類(加工食品)"},{name: "肉類(加工食品)"},{name: "その他 加工食品"},{name: "その他"}])
others_4 = others.children.create(name: "飲料/酒")
others_4.children.create([{name: "コーヒー"},{name: "ソフトドリンク"},{name: "ミネラルウォーター"},{name: "茶"},{name: "ウイスキー"},{name: "ワイン"},{name: "ブランデー"},{name: "焼酎"},{name: "日本酒"},{name: "ビール、発泡酒"},{name: "その他"}])
others_5 = others.children.create(name: "日用品/生活雑貨/旅行")
others_5.children.create([{name: "タオル/バス用品"},{name: "日用品/生活雑貨"},{name: "洗剤/柔軟剤"},{name: "旅行用品"},{name: "防災関連グッズ"},{name: "その他"}])
others_6 = others.children.create(name: "アンティーク/コレクション")
others_6.children.create([{name: "雑貨"},{name: "工芸品"},{name: "家具"},{name: "印刷物"},{name: "その他"}])
others_7 = others.children.create(name: "文房具/事務用品")
others_7.children.create([{name: "筆記具"},{name: "ノート/メモ帳"},{name: "テープ/マスキングテープ"},{name: "カレンダー/スケジュール"},{name: "アルバム/スクラップ"},{name: "ファイル/バインダー"},{name: "はさみ/カッター"},{name: "カードホルダー/名刺管理"},{name: "のり/ホッチキス"},{name: "その他"}])
others_8 = others.children.create(name: "事務/店舗用品")
others_8.children.create([{name: "オフィス用品一般"},{name: "オフィス家具"},{name: "店舗用品"},{name: "OA機器"},{name: "ラッピング/包装"},{name: "その他"}])
others_9 = others.children.create(name: "その他")
others_9.children.create([{name: "すべて"}])